FROM python:3.10-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements-prefect.txt .

RUN pip install --no-cache-dir -r requirements-prefect.txt

COPY . .

EXPOSE 4200

CMD ["prefect", "server", "start", "--host", "0.0.0.0"]
